# Generated by Django 3.2.3 on 2021-05-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_rename_filemodel_newmodel_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmodel',
            name='tech',
            field=models.CharField(default='', max_length=100),
        ),
    ]
